controller_name: 'IdealDiffDriveMPC'
rate: 20
minimum_linear_velocity: 0.1
maximum_linear_velocity: 1.0
maximum_angular_velocity: 0.5
linear_goal_tolerance: 0.5
angular_goal_tolerance: 0.5
id_window_size: 50
horizon_length: 30
linear_state_cost: 1.0
angular_state_cost: 0.0
input_cost_wheel: 0.02
wheel_radius: 0.285
baseline: 1.20
